apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-bwej
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-deploy-tenant/appstudio/dc-metro-map-bwej@sha256:8ac7d223d9758745e0620250ea0c31ea92b2febbdb5731d2d398e01f4db1bf00
        name: my-nodejs
        resources: {}
status: {}
